version: '2'
services:
    afripoint-app:
        image: afripoint
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://afripoint-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=afripoint
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    afripoint-mongodb:
        extends:
            file: mongodb.yml
            service: afripoint-mongodb
